language: node_js
node_js:
  - "10"
install:
  - npm install
stages:
  - "Quality gates"
jobs:
  include:
    - stage: "Quality gates Linter"
      name: "Linter *.js"
      script: npm run lint
    - script: npm run test
      name: "tests"
    - script: npm run stylelint
      name: "Linter *.scss"